### PR TITLE
Implement comment component

### PR DESCRIPTION
**Pull request by AlexanderC**

### CODE REVIEW

**Comment by AlexanderC** [comment]
test

**Comment by devs-deep** [comment]
Test msg on Fri Jul 28 17:44:14 EEST 2017

**Comment by devs-deep** [comment]
Test msg on Fri Jul 28 17:56:15 EEST 2017

**Comment by devs-deep** [comment]
Test msg on Fri Jul 28 17:56:21 EEST 2017

**Comment by devs-deep** [comment]
Test msg on Fri Jul 28 17:56:21 EEST 2017

**Comment by devs-deep** [comment]
Test msg on Fri Jul 28 17:56:22 EEST 2017

**Comment by devs-deep** [comment]
Test msg on Fri Jul 28 17:56:23 EEST 2017

**Comment by devs-deep** [comment]
Test msg on Fri Jul 28 17:57:06 EEST 2017

**Comment by devs-deep** [comment]
Test msg on Fri Jul 28 17:57:12 EEST 2017

**Comment by devs-deep** [comment]
Test msg on Fri Jul 28 17:57:13 EEST 2017

**Pull request closed without merging**
